version: "3.2"
services:
  backend:
    restart: unless-stopped
    container_name: backend
    image: lms_backend:latest
    command : bash -c "python3 manage.py migrate &&
                       python3 manage.py runserver 0.0.0.0:8000"
    build:
      context: ./lms
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    restart: unless-stopped
    container_name: frontend
    image: lms_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
