# Generated by Django 3.2.6 on 2021-10-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='issue_period_weeks',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='request',
            name='issue_period_weeks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='issue_date',
            field=models.DateTimeField(),
        ),
    ]
