# Generated by Django 3.2.6 on 2021-10-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20211021_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='fine_status',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
