# Generated by Django 3.2.6 on 2021-10-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_record_fine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
