# Generated by Django 3.2.6 on 2021-11-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
