# Generated by Django 3.2.6 on 2021-11-09 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_delete_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='1234567', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='language_code',
            field=models.CharField(default='eng', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.CharField(default='No summary found', max_length=5000),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.author', to_field='name'),
        ),
    ]
