# Generated by Django 3.2.6 on 2021-11-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_remove_book_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2),
        ),
    ]
